### ISSUE TITLE
Move installation to pipenv

### ISSUE THREAD

**Issue by shawnmjones** [oduwsdl/MementoEmbed#107]
[Python endorses `pipenv` for dependency management](https://packaging.python.org/guides/tool-recommendations/#application-dependency-management) in projects. This should replace the `requirements.txt` file currently in use.

**Comment by ibnesayeed** [comment]
Yes, I remember suggesting this the other day. Pipfile and pipenv are more modern approaches.

**Comment by shawnmjones** [comment]
Indeed you did suggest it. That's why I looked at it.
