### ISSUE TITLE
parsing multiple Link: response headers

### ISSUE THREAD

**Issue by phonedude** [oduwsdl/MementoEmbed#136]
Martin brought this to my attention.  Here's a sample URL:

https://scholarlyorphans.org/memento/20181009212548/https://ianmilligan.ca/

and it returns two different Link headers:

$ curl -IL https://scholarlyorphans.org/memento/20181009212548/https://ianmilligan.ca/
HTTP/1.1 200 OK
Server: nginx/1.12.1
Content-Type: text/html; charset=UTF-8
Connection: keep-alive
X-Archive-Orig-Server: nginx
Date: Tue, 09 Oct 2018 21:25:48 GMT
X-Archive-Orig-Transfer-Encoding: chunked
X-Archive-Orig-Connection: keep-alive
X-Archive-Orig-Strict-Transport-Security: max-age=86400
X-Archive-Orig-Vary: Accept-Encoding
X-Archive-Orig-Vary: Cookie
X-hacker: If you're reading this, you should visit automattic.com/jobs and apply to join the fun, mention this header.
Link: <https://wp.me/4cEB>; rel=shortlink
X-Archive-Orig-Content-Encoding: gzip
X-ac: 3.sea _bur
Memento-Datetime: Tue, 09 Oct 2018 21:25:48 GMT
Link: <https://ianmilligan.ca/>; rel="original", <https://scholarlyorphans.org/memento/https://ianmilligan.ca/>; rel="timegate", <https://scholarlyorphans.org/memento/timemap/link/https://ianmilligan.ca/>; rel="timemap"; type="application/link-format", <https://scholarlyorphans.org/memento/20181009212548/https://ianmilligan.ca/>; rel="memento"; datetime="Tue, 09 Oct 2018 21:25:48 GMT"; collection="memento"
Content-Location: https://scholarlyorphans.org/memento/20181009212548/https://ianmilligan.ca/
Content-Security-Policy: default-src 'unsafe-eval' 'unsafe-inline' 'self' data: blob: mediastream: ws: wss: ; form-action 'self'

Now, the first header is in error (it should be in X-Archive-orig-Link), but multiple Link headers *are* allowed as per RFC 2616 (and 7230).  Martin said MementoEmbed wasn't finding link rel="original", probably bc it occurs in the 2nd Link header and not the first.

**Comment by shawnmjones** [comment]
It looks like the `requests` library implementation works.

![image](https://user-images.githubusercontent.com/4702031/46827675-7d6d5980-cd56-11e8-9e69-f4b6356bfaab.png)

I will have to test with some other URI-Ms.
