### ISSUE TITLE
Add line ending to all files

### ISSUE THREAD

**Issue by ibnesayeed** [oduwsdl/MementoEmbed#2]
Many files in this repo currently do not have a trailing newline character which is not an standard practice.

**Comment by shawnmjones** [comment]
When a stable, non-alpha, release is created, PEP8 will be run on the source code for analysis, as is customary for Python code. The system is currently being evaluated with Pylint. MementoEmbed is currently in the prototyping phase, and the primary focus at this time is the production of a stable system. If a trailing newline character is requested by the PEP8 script, then I will insert it.  

A trailing newline character does not appear to be required by the style guidelines published by Guido Van Rossum: https://www.python.org/dev/peps/pep-0008/

**Comment by ibnesayeed** [comment]
> A trailing newline character does not appear to be required by the style guidelines published by Guido Van Rossum: https://www.python.org/dev/peps/pep-0008/

This is a more fundamental POSIX standard for textual files than something PEP specific. Many modern text editors have configuration option to automatically add a newline character at the end of every textual file on save, if missing (and this setting is often enabled by default). Read [this StackOverflow thread](https://stackoverflow.com/questions/729692/why-should-text-files-end-with-a-newline) to learn more about the POSIX definition of line.
