### ISSUE TITLE
Actually verify that images exist before using them as a striking image

### ISSUE THREAD

**Issue by shawnmjones** [oduwsdl/MementoEmbed#30]
Sometimes the image returned generates a 404. This could be a temporary archive issue, but we should assume that it just wasn't crawled and isn't available.

**Comment by ibnesayeed** [comment]
If this ticket is about the missing thumbnail image in the card, then looking into the JS console could be helpful to identify the source of the issue. Missing resource seems to be fetched from `http://localhost:5550/undefined`.

**Comment by shawnmjones** [comment]
That is a new problem. Thanks for noting it and please submit it as a new issue.

**Comment by shawnmjones** [comment]
I'm rewriting the image selection algorithm to address this and other issues.
