### ISSUE TITLE
Dockerfile improvements

### ISSUE THREAD

**Issue by ibnesayeed** [oduwsdl/MementoEmbed#33]
```
FROM python:3.6.4-stretch
```

The base image is so specific that it would not update to even any non-breaking security patches (i.e., third point release in the semver scheme) automatically. For example, `python:3.6.4-stretch` is already stale and `python:3.6.5-stretch` is published. We should perhaps use `python:3.6-stretch` instead to accommodate any security patch releases. Better yet, if Python 3.6 is not required specifically and any later version would work then we can use `python:3-stretch` instead.

```
# TODO: publish archiveit_utilities so that we don't need to do this
RUN git clone https://github.com/shawnmjones/archiveit_utilities.git

RUN cd archiveit_utilities && pip install .
```

Each docker instruction adds one layer to the image. It is better to put relevant tasks and any associated cleanup should in a single layer for a cleaner image. Hence, above instructions can be consolidated in a single one.

**Comment by shawnmjones** [comment]
Totally makes sense. I would, however, caution that, as we get close to a release, we do settle on at least a minor version of Python 3.X. In the past, I've had issues with Docker containers and Java libraries where the user left the version numbers set to the equivalent of "latest" and the build stopped working.

**Comment by ibnesayeed** [comment]
For any production system, I would certainly advice against using generic version numbers, especially when there are complex dependencies to worry about. However, as long as a software is using [semver](https://semver.org/), it perhaps is a good idea to keep that third point (i.e., the patch) release flexible to leverage any non-breaking security updates going forward.
