### ISSUE TITLE
Missing thumbnail image in cards

### ISSUE THREAD

**Issue by ibnesayeed** [oduwsdl/MementoEmbed#42]
Every time I try to request a card for a URI-M like `https://web.archive.org/web/20180604110141/http://www.example.com/`, the card is missing the thumbnail image and a 404 is reported in the developer console of the browser which points to a resource at `http://localhost:5550/undefined`. This might be a duplicate of #30.

**Comment by shawnmjones** [comment]
This happens when the image selection algorithm fails to find a striking image for a page. We need a good fallback for the case where no image is found.

**Comment by ibnesayeed** [comment]
A few potential fallbacks include stretched version of the favicon or domain name initials (e.g., letter "E" for www.example.com).

**Comment by shawnmjones** [comment]
I've seen some cards just provide a blank area, but I like the favicon idea as well.

**Comment by ibnesayeed** [comment]
Some sites might be missing even a favicon, so for that you might fall back to initials and then a blank space for domain names in some non-Latin languages where initials might be difficult and sometimes [offensive or unintentional](https://xenforo.com/community/threads/xenforo-2-0-discussion.79603/post-1088763).
