### ISSUE TITLE
Use unobtrusive JavaScript for event listeners

### ISSUE THREAD

**Issue by ibnesayeed** [oduwsdl/MementoEmbed#43]
It's generally not considered a good practice to place JS as HTML attribute value in an obtrusive way so that when all the JS is extracted out into an external file, it does not leak into the markup. The click handler (such as `onclick="requestEmbed();"`) from the following code can be removed and can be bound externally in an unobtrusive way.

```html
<button type="button" class="btn btn-primary" onclick="requestEmbed();">Create a Social Card</button>
<button type="reset" class="btn btn-secondary" onclick="clearEmbed();">Clear URL</button>
```

**Comment by shawnmjones** [comment]
I see your point.
