### ISSUE TITLE
Add a LICENSE file

### ISSUE THREAD

**Issue by ibnesayeed** [oduwsdl/MementoEmbed#5]
We usually use MIT license for most of our codes, but you can chose whichever feels more suitable to you.

**Comment by shawnmjones** [comment]
When an actual release is created, an MIT license will be placed in the repository, just like the rest of the @oduwsdl software. MementoEmbed is currently in the prototyping phase, and the primary focus at this time is the production of a stable system.

**Comment by machawk1** [comment]
@shawnmjones Is there an issue with adding a license in the prototyping phase? Someone may be inspired by whatever method you are using and may be hesitant (if they follow The Rules™) to base code on it, even if they do not intend on using the ultimate MementoEmbed product.

**Comment by ibnesayeed** [comment]
I don't think there is anything wrong in adding a LICENSE from the very beginning as it even allows early contributors to realize how their contributions will eventually be distributed. That said, I understand that the focus at the moment might be to get something out that is working, but some housekeeping tasks are part of the opensource workflow and adding a license should not take too long.

**Comment by shawnmjones** [comment]
You folks make excellent points. I'm still dealing with the realization that this work is public. I will add a license.

**Comment by shawnmjones** [comment]
MIT license has been added.
