### ISSUE TITLE
Split the logging into separate logs for access, errors, application status, etc.

### ISSUE THREAD

**Issue by shawnmjones** [oduwsdl/MementoEmbed#75]
@ibnesayeed suggested splitting the logs into separate files so that data can be more easily gathered for specific tasks, such as analysis of submitted URIs.

So far, I can think of 3 log files:
* access - for logging access to the service, essentially a series of 1-line GETs indicating which URI was requested
* errors - for logging errors
* application - for logging application information for debugging

**Comment by ibnesayeed** [comment]
While access log is important for statistical analysis and should be created in a very strict line-oriented format where one entry belongs to one interaction with the service, the remaining two logs suggested above can be combined in a single debug log. With the help of logging level one can control how detailed this log should be.

**Comment by shawnmjones** [comment]
The logging level is configurable from the configuration file. This will be documented soon.

I've seen some Java applications split normal application output from errors, which is where I got the idea for the 3 logs. I do agree that an access and debug log are probably best. I'm debating if the system needs to be more complex.
