### ISSUE TITLE
Assorted Docker improvements

### ISSUE THREAD

**Issue by ibnesayeed** [oduwsdl/MementoEmbed#81]
Generally [`COPY` is preferred over `ADD`](https://docs.docker.com/develop/develop-images/dockerfile_best-practices/#add-or-copy).

So,

```
ADD . /app
```

Can be changed to:

```
COPY . /app
```

Leverage Docker instructions where possible rather than relying on internal commands.

So,

```
RUN cp docker_appconfig.json /etc/mementoembed.json
```

Can be changed to:

```
COPY docker_appconfig.json /etc/mementoembed.json
```

Also, the included config file is not necessarily a Docker-specific file, so I would rename it to something more general, such as `mementoembed-sample-config.json`.

**Comment by shawnmjones** [comment]
I like these changes. I will make them soon. Thanks.
