### ISSUE TITLE
"undefined" social card generated

### ISSUE THREAD

**Issue by grantat** [oduwsdl/MementoEmbed#85]
URI-M attempted: https://web.archive.org/web/20180320171651/https://dribbble.com/.

![screen shot 2018-07-05 at 10 02 42 am](https://user-images.githubusercontent.com/12538550/42334501-9b735e52-803a-11e8-9ab2-9c716d96786c.png)

Looking at the console for Chrome I found this message:

we have success with json: {"content": "An unforeseen error has occurred with MementoEmbed, please contact the system owner.", "error": "A generic exception was caught by MementoEmbed. Please check the log.", "error details": "'Traceback (most recent call last):\\n  File \"/usr/local/lib/python3.6/site-packages/mementoembed/__init__.py\", line 186, in oembed_endpoint\\n    image = s.striking_image,\\n  File \"/usr/local/lib/python3.6/site-packages/mementoembed/mementosurrogate.py\", line 55, in striking_image\\n    return get_best_image(self.urim, self.httpcache)\\n  File \"/usr/local/lib/python3.6/site-packages/mementoembed/imageselection.py\", line 89, in get_best_image\\n    ctype = r.headers[\\'content-type\\']\\n  File \"/usr/local/lib/python3.6/site-packages/requests/structures.py\", line 52, in __getitem__\\n    return self._store[key.lower()][1]\\nKeyError: \\'content-type\\'\\n'"}

Looks like an error handling issue?

**Comment by shawnmjones** [comment]
Indeed. I'm working on replicating this. Thanks.

**Comment by shawnmjones** [comment]
It should do this.

![2018-07-05_10-31-49](https://user-images.githubusercontent.com/4702031/42335809-ca04af4c-803e-11e8-838b-331564125138.png)

This is still not great, but it's better than a blank social card. I'm not sure why you don't see the error message.

The real problem is generated by one of the images under consideration not returning a content-type header.

**Comment by shawnmjones** [comment]
I have replicated this in the master branch and it does behave as you have noted, which means that the fix is in the `image_selection_failure` branch I am currently working on. Thanks @grantat!

**Comment by shawnmjones** [comment]
I'm recording the exception generated for posterity.

```
2018-07-05 15:56:58,499 [WARNING] mementoembed: An unexpected Exception has been raised for URI-M https://web.archive.org/web/20180320171651/https://dribbble.com
/, details: Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/mementoembed/__init__.py", line 186, in oembed_endpoint
    image = s.striking_image,
  File "/usr/local/lib/python3.6/site-packages/mementoembed/mementosurrogate.py", line 55, in striking_image
    return get_best_image(self.urim, self.httpcache)
  File "/usr/local/lib/python3.6/site-packages/mementoembed/imageselection.py", line 89, in get_best_image
    ctype = r.headers['content-type']
  File "/usr/local/lib/python3.6/site-packages/requests/structures.py", line 52, in __getitem__
    return self._store[key.lower()][1]
KeyError: 'content-type'
```

**Comment by shawnmjones** [comment]
The real fix should occur here, where each image is considered:

https://github.com/oduwsdl/MementoEmbed/blob/ea3c255b5f1987ee5764c25d004f0e09628b3d67/mementoembed/imageselection.py#L95-L126

On line 105, there should be try/except or an if-statement testing for the existence of 'content-type' in the headers. In either case, the failure state should set type to an empty string and then the if-statement on line 109 will continue as usual. This will effectively skip the image for which the web server failed to generate a content-type. Of course, we should also check for a 200 status code from the server right after line 103 as well.

**Comment by shawnmjones** [comment]
This fix generates this social card (after some time):

![2018-07-06_16-51-43](https://user-images.githubusercontent.com/4702031/42403217-e15d4ccc-813c-11e8-92c7-f681ebbf500e.png)
